"""Game update migration

Revision ID: 216543a94ad5
Revises: 22cca601a98c
Create Date: 2024-02-09 17:03:57.647079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216543a94ad5'
down_revision = '22cca601a98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
