"""Game update migration

Revision ID: 22cca601a98c
Revises: 
Create Date: 2024-02-09 13:57:34.883978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cca601a98c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('turn', sa.String(length=20), nullable=True),
    sa.Column('guesser_id', sa.Integer(), nullable=True),
    sa.Column('mastermind_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guesser_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mastermind_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('guess', sa.String(length=4), nullable=True),
    sa.Column('cows', sa.Integer(), nullable=True),
    sa.Column('bulls', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guess')
    op.drop_table('game')
    # ### end Alembic commands ###
